version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: smarttask_postgres
    restart: always
    environment:
      POSTGRES_DB: SmartTaskDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin123!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    networks:
      - smarttask_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: smarttask_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@smarttask.com
      PGADIM_DEFAULT_PASSWORD: Admin123!
    ports:
      - "5050:80"
    depends_on:
      - smarttask_network

  networks:
    smarttask_network:
      driver: bridge
    
    volumes:
      postgres_data:
